# Use a imagem base do Python
FROM python:3.9-slim

# Defina o diretório de trabalho
WORKDIR /app

# Copie o arquivo de requisitos para o contêiner
COPY requirements.txt /app/

# Instale as dependências
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copie o restante do código da aplicação para o contêiner
COPY .. /app/

# Exponha a porta que a aplicação Flask usará
EXPOSE 9000

# Comando para rodar a aplicação
CMD ["python3", "server1.py"]